services:
  - type: web
    name: attendance-backend
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: your-super-secret-production-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString

databases:
  - name: attendance-db
    databaseName: attendance
    user: attendance_user
